//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilibiliUPInfoCollector.Data
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Setting : global::System.Configuration.ApplicationSettingsBase
    {

        private static Setting defaultInstance = ((Setting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Setting())));

        public static Setting Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int AreaID
        {
            get
            {
                return ((int)(this["AreaID"]));
            }
            set
            {
                this["AreaID"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LiveType
        {
            get
            {
                return ((int)(this["LiveType"]));
            }
            set
            {
                this["LiveType"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IntervalHour
        {
            get
            {
                return ((int)(this["IntervalHour"]));
            }
            set
            {
                this["IntervalHour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int IntervalMin
        {
            get
            {
                return ((int)(this["IntervalMin"]));
            }
            set
            {
                this["IntervalMin"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IntervalSecond
        {
            get
            {
                return ((int)(this["IntervalSecond"]));
            }
            set
            {
                this["IntervalSecond"] = value;
            }
        }

        public int Interval
        { get { return (IntervalHour * 60 * 60 + IntervalMin * 60 + IntervalSecond) * 1000; } }
    }

    /*
     * public int Interval
        { get { return (IntervalHour * 60 * 60 + IntervalMin * 60 + IntervalSecond) * 1000; } }
     */
}
